# Importing the Libraries

In [1]:
import pandas as pd
import numpy as np

# Importing the dataset

In [2]:
dataset = pd.read_csv('diabetes.csv')
print('dataset size: ', dataset.shape)
dataset.head(5)

dataset size:  (768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

# Missing data <br> 
Check for missing data

In [3]:
print(dataset.isnull().any())

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool


In [4]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [5]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print('x size: ',x.shape, 'data type of x: ', type(x))
print('y size: ',y.shape, 'data type of y: ', type(y))

x size:  (768, 8) data type of x:  <class 'numpy.ndarray'>
y size:  (768,) data type of y:  <class 'numpy.ndarray'>


# Splitting the dataset into Training and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 0)

In [7]:
x_train.shape

(514, 8)

In [8]:
x_test.shape

(254, 8)

# Feature Scaling<br>
Normalizing data 

In [9]:
#Feature Scaling in this case reduced the accuracy of SVM and Logistic Regression, but increased the accuracy of NB
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#x_train = sc.fit_transform(x_train)
#x_test = sc.transform(x_test)
#pd.DataFrame(x_test).head()

# Applying various classification algorithms to predict result

# Logistic Regression

In [10]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(x_train, y_train)
y_pred_lr = lr.predict(x_test)

/home/sirzechlucifer/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


# Naive-Bayes Classification

In [15]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred_nb = gnb.predict(x_test)

# Support Vector Machine Classification

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state=0)
classifier.fit(x_train, y_train)
y_pred_svm = classifier.predict(x_test)

# Confusion Matrices and Accuracy of each classification algorithm

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
cm_lr = confusion_matrix(y_test, y_pred_lr)
print('Confusion matrix of Logistic regression: ', cm_lr, sep = "\n")
cm_nb = confusion_matrix(y_test, y_pred_nb)
print('Confusion matrix of Naive Bayes: ', cm_nb, sep = "\n")
cm_svm = confusion_matrix(y_test, y_pred_svm)
print('Confusion matrix of Support Vector Machine: ', cm_svm, sep = "\n")

Confusion matrix of Logistic regression: 
[[156  14]
 [ 39  45]]
Confusion matrix of Naive Bayes: 
[[169   1]
 [ 84   0]]
Confusion matrix of Support Vector Machine: 
[[154  16]
 [ 38  46]]


In [14]:
accuracy_lr = accuracy_score(y_test, y_pred_lr)
fscore_lr = f1_score(y_test, y_pred_lr)
print('Logistic Regression\nAccuracy: ', accuracy_lr, '\nF-score', fscore_lr)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
fscore_nb = f1_score(y_test, y_pred_nb)
print('Naive Bayes\nAccuracy: ', accuracy_nb, '\nF-score', fscore_nb)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
fscore_svm = f1_score(y_test, y_pred_svm)
print('Support Vector Machine\nAccuracy: ', accuracy_svm, '\nF-score', fscore_svm)

Logistic Regression
Accuracy:  0.7913385826771654 
F-score 0.6293706293706294
Naive Bayes
Accuracy:  0.6653543307086615 
F-score 0.0
Support Vector Machine
Accuracy:  0.7874015748031497 
F-score 0.6301369863013699
